const colors = require("tailwindcss/colors");

module.exports = {
  presets: [],
  content: [
    // Example content paths...
    "./public/**/*.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    colors: {
      brand: {
        light: "#ffffff",
        dark: "#ffffff",
        DEFAULT: "#ffffff",
      },
      brandBlack: {
        light: "#ffffff",
        dark: "#000000",
        DEFAULT: "#000000",
      },
      brandBrown: "#58595B",
      deepBlue: "#006BC9",
      darkGreen: "#5A6B34",
      deepPurple: "#AA55CE",
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
      yellow: colors.amber,
      green: colors.emerald,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.violet,
      pink: colors.pink,
    },

    safelist: [
      // Custom Colors
      "bg-brand-dark",
      "text-brand-dark",
      "border-brand-dark",
      "bg-brand-light",
      "text-brand-light",
      "border-brand-light",
      "bg-brand",
      "text-brand",
      "border-brand",
      "bg-brand-dark",
      "text-brand-dark",
      "border-brand-dark",
      "bg-brand-light",
      "text-brand-light",
      "border-brand-light",
      "bg-brand",
      "text-brand",
      "border-brand",
      "bg-brandBlack-dark",
      "text-brandBlack-dark",
      "border-brandBlack-dark",
      "bg-brandBlack-light",
      "text-brandBlack-light",
      "border-brandBlack-light",
      "bg-brandBlack",
      "text-brandBlack",
      "border-brandBlack",
      "bg-brandBlack-dark",
      "text-brandBlack-dark",
      "border-brandBlack-dark",
      "bg-brandBlack-light",
      "text-brandBlack-light",
      "border-brandBlack-light",
      "bg-brandBlack",
      "text-brandBlack",
      "border-brandBlack",
    ],
  },
};
